/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package na.phong.study;

import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author qvanphong
 */
public class LoginForm extends javax.swing.JFrame {
//private IOpenRegister openRegis;

    ArrayList<AccInformation> arrList;
    static UserValidate userValidate = new UserValidate();

    /**
     * Creates new form LoginForm
     */
//    ArrayList<AccInformation> acc = AccountData
    public LoginForm() {
        initComponents();
        //Set cho khi ung dung chay se o giua màn hình 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginErrorDialog = new javax.swing.JDialog();
        titlePanelLoginErrorDialog = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblClose1 = new javax.swing.JLabel();
        lblMinimize1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblLoginErrorDialog = new javax.swing.JLabel();
        btnOkLoginErrorDialog = new javax.swing.JButton();
        loginErrorDialog1 = new javax.swing.JDialog();
        titlePanelLoginErrorDialog1 = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        lblClose2 = new javax.swing.JLabel();
        lblMinimize2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblLoginErrorDialog1 = new javax.swing.JLabel();
        btnOkLoginErrorDialog1 = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        usernameTextField = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        loginErrorDialog.setUndecorated(true);

        titlePanelLoginErrorDialog.setBackground(new java.awt.Color(248, 148, 6));

        lblTitle1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Login Error");

        lblClose1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblClose1.setForeground(new java.awt.Color(51, 51, 51));
        lblClose1.setText("X");
        lblClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose1MouseClicked(evt);
            }
        });

        lblMinimize1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblMinimize1.setForeground(new java.awt.Color(51, 51, 51));
        lblMinimize1.setText("_");
        lblMinimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimize1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titlePanelLoginErrorDialogLayout = new javax.swing.GroupLayout(titlePanelLoginErrorDialog);
        titlePanelLoginErrorDialog.setLayout(titlePanelLoginErrorDialogLayout);
        titlePanelLoginErrorDialogLayout.setHorizontalGroup(
            titlePanelLoginErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLoginErrorDialogLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimize1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose1)
                .addGap(16, 16, 16))
        );
        titlePanelLoginErrorDialogLayout.setVerticalGroup(
            titlePanelLoginErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLoginErrorDialogLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(titlePanelLoginErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle1)
                    .addComponent(lblMinimize1)
                    .addComponent(lblClose1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(34, 49, 63));

        lblLoginErrorDialog.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblLoginErrorDialog.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginErrorDialog.setText("Username and password should be insert");

        btnOkLoginErrorDialog.setBackground(new java.awt.Color(89, 171, 227));
        btnOkLoginErrorDialog.setForeground(new java.awt.Color(255, 255, 255));
        btnOkLoginErrorDialog.setText("OK");
        btnOkLoginErrorDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkLoginErrorDialogMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblLoginErrorDialog)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnOkLoginErrorDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblLoginErrorDialog)
                .addGap(18, 18, 18)
                .addComponent(btnOkLoginErrorDialog)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginErrorDialogLayout = new javax.swing.GroupLayout(loginErrorDialog.getContentPane());
        loginErrorDialog.getContentPane().setLayout(loginErrorDialogLayout);
        loginErrorDialogLayout.setHorizontalGroup(
            loginErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titlePanelLoginErrorDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginErrorDialogLayout.setVerticalGroup(
            loginErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginErrorDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(titlePanelLoginErrorDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        loginErrorDialog1.setUndecorated(true);

        titlePanelLoginErrorDialog1.setBackground(new java.awt.Color(248, 148, 6));

        lblTitle2.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("Login Error");

        lblClose2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblClose2.setForeground(new java.awt.Color(51, 51, 51));
        lblClose2.setText("X");
        lblClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose2MouseClicked(evt);
            }
        });

        lblMinimize2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblMinimize2.setForeground(new java.awt.Color(51, 51, 51));
        lblMinimize2.setText("_");
        lblMinimize2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimize2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titlePanelLoginErrorDialog1Layout = new javax.swing.GroupLayout(titlePanelLoginErrorDialog1);
        titlePanelLoginErrorDialog1.setLayout(titlePanelLoginErrorDialog1Layout);
        titlePanelLoginErrorDialog1Layout.setHorizontalGroup(
            titlePanelLoginErrorDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLoginErrorDialog1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimize2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose2)
                .addGap(16, 16, 16))
        );
        titlePanelLoginErrorDialog1Layout.setVerticalGroup(
            titlePanelLoginErrorDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLoginErrorDialog1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(titlePanelLoginErrorDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle2)
                    .addComponent(lblMinimize2)
                    .addComponent(lblClose2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(34, 49, 63));

        lblLoginErrorDialog1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblLoginErrorDialog1.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginErrorDialog1.setText("Username or password is incorrect.");

        btnOkLoginErrorDialog1.setBackground(new java.awt.Color(89, 171, 227));
        btnOkLoginErrorDialog1.setForeground(new java.awt.Color(255, 255, 255));
        btnOkLoginErrorDialog1.setText("OK");
        btnOkLoginErrorDialog1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkLoginErrorDialog1MouseClicked(evt);
            }
        });
        btnOkLoginErrorDialog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkLoginErrorDialog1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnOkLoginErrorDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblLoginErrorDialog1)
                        .addGap(43, 43, 43))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblLoginErrorDialog1)
                .addGap(18, 18, 18)
                .addComponent(btnOkLoginErrorDialog1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginErrorDialog1Layout = new javax.swing.GroupLayout(loginErrorDialog1.getContentPane());
        loginErrorDialog1.getContentPane().setLayout(loginErrorDialog1Layout);
        loginErrorDialog1Layout.setHorizontalGroup(
            loginErrorDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titlePanelLoginErrorDialog1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginErrorDialog1Layout.setVerticalGroup(
            loginErrorDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginErrorDialog1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(titlePanelLoginErrorDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        titlePanel.setBackground(new java.awt.Color(248, 148, 6));

        lblTitle.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Login Form");

        lblClose.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblClose.setForeground(new java.awt.Color(51, 51, 51));
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        lblMinimize.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(51, 51, 51));
        lblMinimize.setText("_");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose)
                .addGap(16, 16, 16))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(lblMinimize)
                    .addComponent(lblClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bodyPanel.setBackground(new java.awt.Color(34, 49, 63));
        bodyPanel.setForeground(new java.awt.Color(254, 254, 254));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Username: ");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Password:");

        PasswordField.setBackground(new java.awt.Color(254, 254, 254));

        usernameTextField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(89, 171, 227));
        btnLogin.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(231, 76, 60));
        btnCancel.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Don't have account? Click here to register.");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bodyPanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bodyPanelLayout.createSequentialGroup()
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PasswordField)
                            .addComponent(usernameTextField)))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (usernameTextField.getText().isEmpty() || PasswordField.getText().isEmpty()) {
            loginErrorDialog.setVisible(true);
            loginErrorDialog.pack();
            loginErrorDialog.setLocationRelativeTo(null);
            System.out.println("Available accounts: ");
            for (AccInformation a : userValidate.getArrList()) {
                System.out.println(a.getUsername() + "-" + a.getPassword());
            }
        } else {
            if (userValidate.findInDatabase(usernameTextField.getText(), PasswordField.getText(), userValidate.getArrList())) {
                //Show Dialog Welcome then shutdown
                //WIP
                System.exit(0);
            } else {
                loginErrorDialog1.setVisible(true);
                loginErrorDialog1.setTitle("Error");
                loginErrorDialog1.pack();
                loginErrorDialog1.setLocationRelativeTo(null);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void lblClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose1MouseClicked
        // TODO add your handling code here:
//        System.exit(0);
        loginErrorDialog.dispose();
    }//GEN-LAST:event_lblClose1MouseClicked

    private void lblMinimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimize1MouseClicked
        // TODO add your handling code here:
        setState(ICONIFIED);
    }//GEN-LAST:event_lblMinimize1MouseClicked

    private void btnOkLoginErrorDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkLoginErrorDialogMouseClicked
        // TODO add your handling code here:
        loginErrorDialog.dispose();
    }//GEN-LAST:event_btnOkLoginErrorDialogMouseClicked

    private void lblClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose2MouseClicked
        // TODO add your handling code here:
        loginErrorDialog1.dispose();
    }//GEN-LAST:event_lblClose2MouseClicked

    private void lblMinimize2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimize2MouseClicked
        // TODO add your handling code here:
        setState(ICONIFIED);
    }//GEN-LAST:event_lblMinimize2MouseClicked

    private void btnOkLoginErrorDialog1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkLoginErrorDialog1MouseClicked
        // TODO add your handling code here:
        loginErrorDialog1.dispose();
    }//GEN-LAST:event_btnOkLoginErrorDialog1MouseClicked

    private void btnOkLoginErrorDialog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkLoginErrorDialog1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkLoginErrorDialog1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        RegisterForm registerForm = new RegisterForm(userValidate);
        registerForm.setVisible(true);
        registerForm.pack();
        registerForm.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                userValidate = new UserValidate();
//                new LoginForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnOkLoginErrorDialog;
    private javax.swing.JButton btnOkLoginErrorDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblClose1;
    private javax.swing.JLabel lblClose2;
    private javax.swing.JLabel lblLoginErrorDialog;
    private javax.swing.JLabel lblLoginErrorDialog1;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblMinimize1;
    private javax.swing.JLabel lblMinimize2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JDialog loginErrorDialog;
    private javax.swing.JDialog loginErrorDialog1;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel titlePanelLoginErrorDialog;
    private javax.swing.JPanel titlePanelLoginErrorDialog1;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
//    public interface IOpenRegister{
//    public void openRegister();
//}
}
